--- 
count: 10
default: 
  restart: 0
  wait: 0
editor: 
  files: 
    eg: 
      - some-file.eg
name: monstor-monitor
terminals: 
  10: []

  2: []

  3: []

  4: []

  5: []

  6: []

  7: []

  8: []

  9: []

